version: '3.9'

services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - network

  redis:
    image: redis:transcendence
    pull_policy: never
    build:
      context: ./redis
      dockerfile: Dockerfile
    container_name: redis
    networks:
      - network

  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    working_dir: /backend
    ports:
      - "8000:8000"
    networks:
      - network

volumes:
  postgres_data:

networks:
  network:
    name: network
    driver: bridge